SRC=main.cpp Matrix.cpp FlareMap.cpp ShaderProgram.cpp
LDFLAGS=-lstdc++ -lm -lSDL2 -lGLEW -lGL
CFLAGS=-Wall -I/usr/include/SDL2
default:
	g++ -std=c++11 $(CFLAGS) $(SRC) $(LDFLAGS) -DLINUX -o HW4
#./Matrix.h ./ShaderProgram.h ./Matrix.cpp ./ShaderProgram.cpp 
